alaviss/nim-sys

- src/sys/strings.nim
- tests/strings/tnulless.nim
Not every character in a string is valid for certain OS APIs, so we need
a typesafe way to declare strings with such requirements.
Fixes #2
> sys/strings: add module for special string types

- .github/workflows/ci.yml
- readme.md
- src/sys/files.nim
- src/sys/ioqueue.nim
- src/sys/pipes.nim
- src/sys/private/files_posix.nim
- src/sys/private/files_windows.nim
- sys.nimble
- tests/ioqueue/asyncio.nim
- tests/ioqueue/tqueue.nim
- tests/ioqueue/tready.nim
- tests/ioqueue/tunregister.nim
- tests/pipes/tpipe.nim
- Raise sys' Nim version requirement to be at least 1.5.1
- Removed all gating conditional for Nim < 1.5.1
- Clarified some documentation on `read`, `write`
- Migrated all asyncdispatch-based interfaces to CPS
> sys(treewide): replace asyncdispatch with ioqueue

- sys.nimble
This is necessary to support newer compilers.
> sys(treewide): update to cps 0.4.2

- sys.nimble
CPS has already changed home to nim-works. The new release also brought
in the removal of `()` operator which has been causing trouble in the
past with generics in nim-sys.
> sys(treewide): update cps to 0.6.0

- src/sys/handles.nim
- src/sys/ioqueue.nim
- src/sys/ioqueue/iocp.nim
- src/sys/private/files_posix.nim
- src/sys/private/files_windows.nim
- src/sys/private/handles_posix.nim
- src/sys/private/handles_windows.nim
- src/sys/private/ioqueue_bsd.nim
- src/sys/private/ioqueue_linux.nim
- tests/handles/tdestroy.nim
- tests/ioqueue/asyncio.nim
Since https://github.com/nim-lang/Nim/issues/19139 was closed as a
"won't fix", the "workaround" has to become permanent.
If we are to store a boolean next to the FD, it would double the
structure size, which is undesirable.
Instead, storage is now done via a lossless map so that zero-ed values
are invalid by default.
In this commit, Handle[T] API is changed to match other parts of the
project. In short:
* `get` -> `fd`
* `take` -> `takeFd`
> handles: change storage strategy and conform API

- .github/workflows/ci.yml
- .gitignore
- src/sys/files.nim
- src/sys/private/errors.nim
- src/sys/private/files_windows.nim
- sys.nimble
- tests/ioqueue/asyncio.nim
- tests/ioqueue/tqueue.nim
- tests/ioqueue/tready.nim
- tests/ioqueue/tunregister.nim
- tests/pipes/tpipe.nim
Unfortunately this feature has been removed from upstream Nim.
This makes the API terrible to use, but we have to deal with it for now.
> sys(treewide): purge implicitDeref from the codebase

- sys.nimble
Latest development version of Nim contains breaking changes that requires newer version of CPS that is incompatible with older Nim.
> sys(treewide): use CPS 0.9.x for Nim >= 1.9.0

- src/sys/private/syscall/bsd/kqueue.nim
- src/sys/private/syscall/bsd/kqueue_fbsd.ld
Testing shown that the linker script does not work and I could not make it work, so the alternative is to use FreeBSD 12+ structure.
> syscall/kqueue: use FreeBSD 12 and newer structures

- src/sys/ioqueue.nim
- src/sys/ioqueue/iocp.nim
- src/sys/private/addresses_posix.nim
- src/sys/private/addresses_windows.nim
- src/sys/private/ioqueue_bsd.nim
- src/sys/private/ioqueue_linux.nim
- src/sys/private/sockets_posix.nim
- src/sys/private/sockets_windows.nim
- src/sys/private/syscall/posix.nim
- src/sys/sockets.nim
- src/sys/sockets/addresses.nim
- sys.nimble
- tests/helpers/io.nim
- tests/sockets/tip.nim
- tests/sockets/tsockets.nim
- tests/sockets/tsockets.nims
Design:
- `Socket` base for common operations
- Specialized `Conn[Protocol]` and `Listener[Protocol]`
- `Conn`:
- `connect`, `read` and `write` as basic primitives
- `Listener`:
- `listen`, `accept` as basic primitives
Current progress:
Closes #22
> sys/sockets: initial implementation for a networking interface

- src/sys/paths.nim
- src/sys/private/paths_posix.nim
- src/sys/private/paths_windows.nim
- src/sys/private/strsliceutils.nim
- src/sys/strings.nim
- tests/paths/tposix.nim
- tests/paths/twindows.nim
Fixes #1 
This initial implementation targets only use cases of `sys/exec`.
Status:
> sys/paths: a cross-platform path manipulation library

- .github/workflows/ci.yml
- On Windows, use compiler from winlibs project.
- On Linux, use the i686 cross compiler.
- Pages are now uploaded using deploy-pages.
- Updated actions/checkout
> ci: rework compiler selection and docs deployment

- src/sys/private/ioqueue_linux.nim
queue() being a generic caused trouble in generic sandwich prone cases. queue() has not needed to be a generic taking AnyFD for quite awhile now, so this fix is simply a prototype change.
> ioqueue(linux): make queue a concrete procedure

- src/sys/private/sockets_posix.nim
- src/sys/private/sockets_windows.nim
This flag implementation is known to be troublesome: https://fedoraproject.org/wiki/QA/Networking/NameResolution/ADDRCONFIG
Also, it would prevent users from explicitly requesting for IPv6 addresses on systems where *outbound* IPv6 is not available, which might be a surprising behavior.
According to Fedora's documentation, glibc will sort the addresses so that the best address is the first one, so this flag does not give us a lot in terms of optimization there.
> sockets: drop AI_ADDRCONFIG from getaddrinfo calls

- src/sys/private/addresses_posix.nim
- src/sys/private/addresses_windows.nim
- src/sys/private/sockets_posix.nim
- src/sys/private/sockets_windows.nim
- src/sys/private/syscall/posix.nim
- src/sys/sockets.nim
- src/sys/sockets/addresses.nim
- sys.nimble
- tests/sockets/tip.nim
- tests/sockets/tsockets.nim
With the current prototype, I'm opting for keeping the transport protocol address family agnostic. This means that variants have to be used to distinguish between IPv4 and IPv6 addresses, but simplifies the typical usage of data transport drastically by not requiring strict type disambiguation.
I might revisit making TCP4/TCP6 sockets a thing when a form of polymorphism exists for the language.
Breaking changes:
- resolveIP4 -> resolveIP
- addressing APIs now return IPEndpoint, which could be either IP4 or IP6 endpoint
Implementation status:
- Platforms
~~Blocked by: https://github.com/nim-works/cps/issues/301~~ Fixed with CPS 0.10.1
> sockets: prototype for ipv6

- .github/workflows/ci.yml
Skip workflow run if any of the following are true:
* Only files that are not relevant to docgen/code were modified.
* If the same workflow is run twice (ie. for push and PR).
Cancel runs if any of the following are true:
* If the current workflow run is obsolete.
> ci: skip or cancel redundant/outdated runs

- .github/workflows/ci.yml
Only run workflow on PR and pushes to master.
This replaces concurrent_skipping as the feature did not distinguish correctly between PRs and pushes, allowing PRs to skip required checks.
> ci: replace concurrent_skipping with PR-only runs

- .github/workflows/ci.yml
The artifact is packaged nicely into a .tar file. All we have to do is to reupload it instead of running the whole upload-pages again.
> ci: don't double wrap page artifact

- src/sys/private/sockets_posix.nim
- src/sys/private/sockets_windows.nim
- tests/sockets/tip.nim
The expression we used for `getaddrinfo()` invocation might cause the underlying strings to be deallocated before they are sent to `getaddrinfo()`, which would result in use-after-free issues.
Also added more tests for resolveIP + having a port set.
> sockets: fix string lifetime for getaddrinfo

- src/sys/private/files_posix.nim
- src/sys/private/files_windows.nim
- src/sys/sockets.nim
In these situations there are only two reasons why cleaning up fails:
* The FD is invalid
* There is something wrong with the OS
The first case is already covered by Defects, which are not ignored, and we can't do anything (nor can the caller) for the second case, so just ignore those.
This is brought on by nimskull 0.1.0-dev.21268, which disallows raise in hooks since that was undefined behavior.
> files, sockets: ignore cleanup exceptions on =destroy

- src/sys/private/sockets_posix.nim
- src/sys/sockets.nim
- tests/sockets/tsockets.nim
Platform specific stuff is best avoided but Unix sockets should be used when they are available.
I've only tested on Linux.
> Unix sockets

- .github/workflows/ci.yml
- .gitmodules
- src/sys/ioqueue/iocp.nim
- src/sys/private/addresses_windows.nim
- src/sys/private/files_windows.nim
- src/sys/private/handles_windows.nim
- src/sys/private/pipes_windows.nim
- src/sys/private/sockets_windows.nim
- sys.nimble
- tests/handles/tdestroy.nim
- tests/handles/tinherit.nim
- tests/helpers/handles.nim
- tests/ioqueue/asyncio.nim
Remove winim submodule as the main package is now installable on non-Windows platforms.
> sys(treewide): unbundle winim

- .github/dependabot.yml
Group all minor and patch updates together, as they're typically safe to go in one unit.
> dependabot: group GitHub Actions updates
